"""migrate1

Revision ID: ea412a01bcb4
Revises: 
Create Date: 2025-04-17 17:20:03.377770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea412a01bcb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_constraint('categorias_icono_key', type_='unique')
        batch_op.drop_constraint('categorias_nombre_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.create_unique_constraint('categorias_nombre_key', ['nombre'])
        batch_op.create_unique_constraint('categorias_icono_key', ['icono'])

    # ### end Alembic commands ###
